apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 851725348477.dkr.ecr.ap-south-1.amazonaws.com/hello-fastapi:latest
        ports:
        - containerPort: 80

